In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1=np.arange(9).reshape(3,3)

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1 = Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index=['X','Y'])

In [7]:
ser1

T    0
U    1
V    2
dtype: int64

In [8]:
ser2

X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [10]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [12]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y',"Z"])
dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [13]:
dframe1

X         Y         Z
0  0.747496 -0.164036  1.005889
1 -0.690469  0.245225  0.562355
2 -0.352378 -0.252971  0.576838
3 -0.753950 -2.343584 -0.344283

In [14]:
dframe2

Y         Q         X
0  0.146352  1.597755  0.402096
1 -1.354602 -0.171486  0.183705
2  0.122061  1.268539  0.751365

In [15]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN  0.747496 -0.164036  1.005889
1       NaN -0.690469  0.245225  0.562355
2       NaN -0.352378 -0.252971  0.576838
3       NaN -0.753950 -2.343584 -0.344283
0  1.597755  0.402096  0.146352       NaN
1 -0.171486  0.183705 -1.354602       NaN
2  1.268539  0.751365  0.122061       NaN

In [16]:
pd.concat([dframe1,dframe1],ignore_index=True)

X         Y         Z
0  0.747496 -0.164036  1.005889
1 -0.690469  0.245225  0.562355
2 -0.352378 -0.252971  0.576838
3 -0.753950 -2.343584 -0.344283
4  0.747496 -0.164036  1.005889
5 -0.690469  0.245225  0.562355
6 -0.352378 -0.252971  0.576838
7 -0.753950 -2.343584 -0.344283